# Generated by Django 4.2.5 on 2023-09-20 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="email",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="last_name",
        ),
        migrations.AddField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                default=-1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
