# Generated by Django 4.2.5 on 2023-09-22 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "organization",
            "0002_remove_employee_email_remove_employee_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="office",
            name="location",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="organization.location"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="location",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="organization.location"
            ),
        ),
    ]
